# Generated by Django 4.2.26 on 2025-11-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='park',
            name='coordinates',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='park',
            name='date_established',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='park',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='park',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='park',
            name='visitors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='park',
            name='wikipedia_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
