# Generated by Django 4.2.26 on 2025-11-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park_images', '0002_park_area_park_coordinates_park_date_established_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkimage',
            old_name='image_name',
            new_name='display_name',
        ),
    ]
