# Generated by Django 4.2.26 on 2025-11-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park_images', '0003_rename_image_name_parkimage_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='code',
        ),
    ]
