# Generated by Django 4.2.26 on 2025-11-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_images', '0004_remove_park_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='name',
            new_name='image_key',
        ),
        migrations.AddField(
            model_name='parkimage',
            name='image_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
